// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyRename(arg1) {
  return window['go']['main']['App']['ApplyRename'](arg1);
}

export function GetFileInfos(arg1) {
  return window['go']['main']['App']['GetFileInfos'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function PreviewRename(arg1, arg2) {
  return window['go']['main']['App']['PreviewRename'](arg1, arg2);
}
