// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyRename(arg1:Array<main.PreviewResult>):Promise<Array<main.RenameResult>>;

export function GetFileInfos(arg1:Array<string>):Promise<Array<main.FileInfo>>;

export function OpenFileDialog():Promise<Array<main.FileInfo>>;

export function PreviewRename(arg1:Array<main.FileInfo>,arg2:Array<main.RenameRule>):Promise<Array<main.PreviewResult>>;
